name: 'PHP Code Review'
description: 'Automated PHP code review using Cursor Agent - optimized for PHP 8.4, Doctrine ORM, Symfony, PSR-12'
inputs:
  cursor_api_key:
    description: 'Cursor API key'
    required: true
  model:
    description: 'Model to use for review'
    required: false
    default: 'auto'
  blocking_review:
    description: 'Enable blocking review (fail workflow on critical issues 🚨 or 🔒). If true, workflow will fail if critical issues are found.'
    required: false
    default: 'false'
  gh_token:
    description: 'GitHub/Gitea token for PR comments'
    required: true
  custom_prompt:
    description: 'Custom prompt to override default code review instructions. If provided, this will be used instead of the default prompt.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Cursor CLI
      shell: bash
      run: |
        set -e
        curl https://cursor.com/install -fsS | bash
        # Добавляем в PATH для текущего и последующих шагов
        if [ -n "$GITHUB_PATH" ]; then
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        else
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        fi
        export PATH="$HOME/.local/bin:$PATH"

    - name: Verify Cursor CLI installation
      shell: bash
      run: |
        if ! command -v cursor-agent &> /dev/null; then
          echo "❌ cursor-agent not found in PATH"
          exit 1
        fi
        echo "✅ cursor-agent installed successfully"
        cursor-agent --version || true

    - name: Configure git identity
      shell: bash
      run: |
        git config user.name "Cursor Agent"
        git config user.email "cursoragent@cursor.com"

    - name: Perform automated PHP code review
      shell: bash
      env:
        CURSOR_API_KEY: ${{ inputs.cursor_api_key }}
        MODEL: ${{ inputs.model }}
        GH_TOKEN: ${{ inputs.gh_token }}
        BLOCKING_REVIEW: ${{ inputs.blocking_review }}
        CUSTOM_PROMPT: ${{ inputs.custom_prompt }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GITHUB_PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
      run: |
        if [ -n "$CUSTOM_PROMPT" ]; then
          echo "Using custom prompt"
          echo "$CUSTOM_PROMPT" | cursor-agent --force --model "$MODEL" --output-format=text --print
        else
          echo "Using PHP-specific prompt"
          cursor-agent --force --model "$MODEL" --output-format=text --print <<PROMPT
        You are performing automated code review for a PHP 8.4 project using Doctrine ORM, Symfony components, and PSR-12 coding standards. The gh CLI is available and authenticated via GH_TOKEN. You may comment on pull requests.

        Project context:
        - Language: PHP 8.4 with strict types required
        - Framework: Symfony components (DI, Validator, Serializer, Console, etc.)
        - ORM: Doctrine ORM 2.12+
        - Coding standard: PSR-12 with PHP-CS-Fixer
        - Static analysis: Psalm (error level 1)
        - Testing: PHPUnit 10+
        - Architecture: Modular structure with dependency injection

        Context:
        - Repo: ${GITHUB_REPOSITORY}
        - PR Number: ${GITHUB_PR_NUMBER}
        - PR Head SHA: ${GITHUB_PR_HEAD_SHA}
        - PR Base SHA: ${GITHUB_PR_BASE_SHA}
        - Blocking Review: ${BLOCKING_REVIEW}

        Objectives:
        1) Re-check existing review comments and reply resolved when addressed.
        2) Review the current PR diff and flag clear, high-severity issues.
        3) Verify that the code implementation matches the PR description and requirements.
        4) Leave very short inline comments (1-2 sentences) on changed lines only and a brief summary at the end.

        Procedure:
        - Get PR description and title: gh pr view --json title,body,number
        - Get existing comments: gh pr view --json comments
        - Get diff: gh pr diff
        - Get changed files with patches: gh api repos/${GITHUB_REPOSITORY}/pulls/${GITHUB_PR_NUMBER}/files --paginate --jq '.[] | {filename,patch}'
        - Compute exact inline anchors for each issue (file path + diff position). Comments MUST be placed inline on the changed line in the diff, not as top-level comments.
        - Detect prior top-level "no issues" style comments authored by this bot (match bodies like: "✅ no issues", "No issues found", "LGTM").
        - If CURRENT run finds issues and any prior "no issues" comments exist:
          - Prefer to remove them to avoid confusion:
            - Try deleting top-level issue comments via: gh api -X DELETE repos/${GITHUB_REPOSITORY}/issues/comments/<comment_id>
            - If deletion isn't possible, minimize them via GraphQL (minimizeComment) or edit to prefix "[Superseded by new findings]".
          - If neither delete nor minimize is possible, reply to that comment: "⚠️ Superseded: issues were found in newer commits".
        - If a previously reported issue appears fixed by nearby changes, reply: ✅ This issue appears to be resolved by the recent changes

        Analyze for:

        **1. Requirements compliance** 📋:
        - Check if the code implements what is described in the PR title and body
        - Flag if key requirements from PR description are missing or incomplete
        - Flag if implementation doesn't match the stated purpose
        - Flag if expected functionality is not implemented
        - Flag if edge cases mentioned in PR are not handled

        **2. PHP 8.4 & strict types** 🐛:
        - Missing `declare(strict_types=1);` at the top of new PHP files (REQUIRED)
        - Missing or incorrect type declarations (parameters, return types, properties)
        - Use of deprecated PHP functions or features
        - Incorrect null handling (should use null coalescing operator ?? or nullsafe operator ?-> where appropriate)
        - Missing property type declarations (PHP 7.4+)
        - Incorrect union types or intersection types usage
        - Missing readonly properties where appropriate (PHP 8.1+)
        - Incorrect enum usage (PHP 8.1+)

        **3. Doctrine ORM** 🗄️:
        - Missing or incorrect entity relationships (OneToMany, ManyToOne, ManyToMany, OneToOne)
        - N+1 query problems (missing eager loading, incorrect fetch mode)
        - Missing indexes on frequently queried fields
        - Incorrect cascade operations (cascade={"persist", "remove"} etc.)
        - Missing or incorrect entity lifecycle callbacks (PrePersist, PostLoad, etc.)
        - Transaction management issues (missing flush, incorrect transaction boundaries)
        - Missing or incorrect entity validation constraints
        - Incorrect use of Doctrine QueryBuilder (SQL injection risks)
        - Missing DQL parameter binding
        - Incorrect entity hydration

        **4. Symfony components** 🔧:
        - Incorrect dependency injection (missing type hints, circular dependencies)
        - Missing service configuration or incorrect service definitions
        - Incorrect use of Symfony Validator (missing constraints, incorrect validation groups)
        - Incorrect use of Symfony Serializer (missing normalization, incorrect groups)
        - Missing or incorrect event dispatching
        - Incorrect console command structure
        - Missing or incorrect configuration handling

        **5. Security** 🔒:
        - SQL injection vulnerabilities (especially in raw queries)
        - XSS vulnerabilities (missing output escaping)
        - Missing input validation
        - Incorrect authentication/authorization checks
        - Sensitive data exposure (passwords, tokens in logs)
        - Missing CSRF protection where needed
        - Incorrect file upload handling
        - Path traversal vulnerabilities

        **6. Performance** ⚡:
        - N+1 query problems in Doctrine
        - Missing database indexes
        - Inefficient loops or array operations
        - Missing caching where appropriate
        - Memory leaks (circular references, large object retention)
        - Unnecessary database queries
        - Missing pagination for large datasets

        **7. Code quality & PSR-12** 🔍:
        - PSR-12 violations (indentation, spacing, naming conventions)
        - Missing or incorrect PHPDoc blocks (especially @param, @return, @throws)
        - Overly complex functions (high cyclomatic complexity > 10)
        - Magic numbers/strings that should be constants
        - Dead code or unreachable code
        - Missing or incorrect error messages
        - Code duplication that should be extracted
        - Incorrect namespace usage or PSR-4 violations
        - Missing use statements or unused imports

        **8. Error handling** ⚠️:
        - Missing error handling for critical operations
        - Catching generic Exception instead of specific exceptions
        - Swallowing errors silently
        - Missing try-catch blocks where needed
        - Incorrect exception messages (not descriptive enough)
        - Missing logging of errors

        **9. Architecture & SOLID** 🏗️:
        - Violations of SOLID principles (especially Single Responsibility)
        - Tight coupling between components
        - Missing or incorrect use of design patterns
        - Incorrect dependency injection usage
        - Missing interfaces where abstraction is needed
        - God classes or methods (too many responsibilities)

        **10. Testing** 🧪:
        - Missing tests for new functionality (if test files exist in project)
        - Incorrect test structure (if modifying existing tests)
        - Missing test coverage for edge cases

        Commenting rules:
        - Max 10 inline comments total; prioritize the most critical issues
        - One issue per comment; place on the exact changed line
        - All issue comments MUST be inline (anchored to a file and line/position in the PR diff)
        - Natural tone, specific and actionable; do not mention automated or high-confidence
        - Use emojis: 🚨 Critical 🔒 Security ⚡ Performance ⚠️ Logic ✅ Resolved ✨ Improvement 📋 Requirements 🏗️ Architecture 🐛 PHP 🗄️ Doctrine 🔧 Symfony 🔍 Code Quality 🧪 Testing

        Submission:
        - If there are NO issues to report and an existing top-level comment indicating "no issues" already exists (e.g., "✅ no issues", "No issues found", "LGTM"), do NOT submit another comment. Skip submission to avoid redundancy.
        - If there are NO issues to report and NO prior "no issues" comment exists, submit one brief summary comment noting no issues.
        - If there ARE issues to report and a prior "no issues" comment exists, ensure that prior comment is deleted/minimized/marked as superseded before submitting the new review.
        - If there ARE issues to report, submit ONE review containing ONLY inline comments plus an optional concise summary body. Use the GitHub Reviews API to ensure comments are inline:
        - Build a JSON array of comments like: [{ "path": "<file>", "position": <diff_position>, "body": "..." }]
        - Submit via: gh api repos/${GITHUB_REPOSITORY}/pulls/${GITHUB_PR_NUMBER}/reviews -f event=COMMENT -f body="\$SUMMARY" -f comments='[\$COMMENTS_JSON]'
        - Do NOT use: gh pr review --approve or --request-changes

        Blocking behavior:
        - If BLOCKING_REVIEW is true and any 🚨 or 🔒 issues were posted: echo "CRITICAL_ISSUES_FOUND=true" >> \$GITHUB_ENV
        - Otherwise: echo "CRITICAL_ISSUES_FOUND=false" >> \$GITHUB_ENV
        - Always set CRITICAL_ISSUES_FOUND at the end
        PROMPT
        fi

    - name: Check blocking review results
      if: ${{ inputs.blocking_review == 'true' }}
      shell: bash
      run: |
        echo "Checking for critical issues..."
        echo "CRITICAL_ISSUES_FOUND: ${CRITICAL_ISSUES_FOUND:-unset}"

        if [ "${CRITICAL_ISSUES_FOUND:-false}" = "true" ]; then
          echo "❌ Critical issues found and blocking review is enabled. Failing the workflow."
          exit 1
        else
          echo "✅ No blocking issues found."
        fi

