name: 'Cursor Code Review'
description: 'Automated code review using Cursor Agent'
inputs:
  cursor_api_key:
    description: 'Cursor API key'
    required: true
  model:
    description: 'Model to use for review'
    required: false
    default: 'auto'
  blocking_review:
    description: 'Enable blocking review (fail workflow on critical issues 🚨 or 🔒). If true, workflow will fail if critical issues are found.'
    required: false
    default: 'false'
  gh_token:
    description: 'GitHub/Gitea token for PR comments'
    required: true
  custom_prompt:
    description: 'Custom prompt to override default code review instructions. If provided, this will be used instead of the default prompt.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Cursor CLI
      shell: bash
      run: |
        set -e
        curl https://cursor.com/install -fsS | bash
        # Добавляем в PATH для текущего и последующих шагов
        if [ -n "$GITHUB_PATH" ]; then
          echo "$HOME/.local/bin" >> $GITHUB_PATH
        else
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        fi
        export PATH="$HOME/.local/bin:$PATH"

    - name: Verify Cursor CLI installation
      shell: bash
      run: |
        if ! command -v cursor-agent &> /dev/null; then
          echo "❌ cursor-agent not found in PATH"
          exit 1
        fi
        echo "✅ cursor-agent installed successfully"
        cursor-agent --version || true

    - name: Configure git identity
      shell: bash
      run: |
        git config user.name "Cursor Agent"
        git config user.email "cursoragent@cursor.com"

    - name: Perform automated code review
      shell: bash
      env:
        CURSOR_API_KEY: ${{ inputs.cursor_api_key }}
        MODEL: ${{ inputs.model }}
        GH_TOKEN: ${{ inputs.gh_token }}
        BLOCKING_REVIEW: ${{ inputs.blocking_review }}
        CUSTOM_PROMPT: ${{ inputs.custom_prompt }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GITHUB_PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
      run: |
        if [ -n "$CUSTOM_PROMPT" ]; then
          echo "Using custom prompt"
          echo "$CUSTOM_PROMPT" | cursor-agent --force --model "$MODEL" --output-format=text --print
        else
          echo "Using default prompt"
          cursor-agent --force --model "$MODEL" --output-format=text --print <<PROMPT
        You are operating in a GitHub Actions runner performing automated code review. The gh CLI is available and authenticated via GH_TOKEN. You may comment on pull requests.

        Context:
        - Repo: ${GITHUB_REPOSITORY}
        - PR Number: ${GITHUB_PR_NUMBER}
        - PR Head SHA: ${GITHUB_PR_HEAD_SHA}
        - PR Base SHA: ${GITHUB_PR_BASE_SHA}
        - Blocking Review: ${BLOCKING_REVIEW}

        Objectives:
        1) Re-check existing review comments and reply resolved when addressed.
        2) Review the current PR diff and flag only clear, high-severity issues.
        3) Verify that the code implementation matches the PR description and requirements.
        4) Leave very short inline comments (1-2 sentences) on changed lines only and a brief summary at the end.

        Procedure:
        - Get PR description and title: gh pr view --json title,body,number
        - Get existing comments: gh pr view --json comments
        - Get diff: gh pr diff
        - Get changed files with patches to compute inline positions: gh api repos/${GITHUB_REPOSITORY}/pulls/${GITHUB_PR_NUMBER}/files --paginate --jq '.[] | {filename,patch}'
        - Compute exact inline anchors for each issue (file path + diff position). Comments MUST be placed inline on the changed line in the diff, not as top-level comments.
        - Detect prior top-level "no issues" style comments authored by this bot (match bodies like: "✅ no issues", "No issues found", "LGTM").
        - If CURRENT run finds issues and any prior "no issues" comments exist:
        - Prefer to remove them to avoid confusion:
            - Try deleting top-level issue comments via: gh api -X DELETE repos/${GITHUB_REPOSITORY}/issues/comments/<comment_id>
            - If deletion isn't possible, minimize them via GraphQL (minimizeComment) or edit to prefix "[Superseded by new findings]".
        - If neither delete nor minimize is possible, reply to that comment: "⚠️ Superseded: issues were found in newer commits".
        - If a previously reported issue appears fixed by nearby changes, reply: ✅ This issue appears to be resolved by the recent changes
        - Analyze for:
        - **Requirements compliance**: Check if the code implements what is described in the PR title and body. Flag if:
          * Key requirements from PR description are missing or incomplete
          * Implementation doesn't match the stated purpose
          * Expected functionality is not implemented
          * Edge cases mentioned in PR are not handled
        - **Technical issues** (language-agnostic):
          * Null/undefined dereferences
          * Resource leaks (unclosed files or connections)
          * Injection (SQL/XSS)
          * Concurrency/race conditions
          * Missing error handling for critical operations
          * Obvious logic errors with incorrect behavior
          * Clear performance anti-patterns with measurable impact
          * Definitive security vulnerabilities
        - **Architecture & patterns**:
          * Violations of SOLID principles (especially Single Responsibility)
          * Incorrect dependency injection usage
          * Tight coupling between components
          * Missing or incorrect use of design patterns
          * Code duplication that should be extracted
        - **API & documentation**:
          * Missing or incorrect API documentation
          * Incorrect HTTP status codes
          * Missing input validation
          * Incorrect response formats
          * Missing error response handling
        - **Code quality**:
          * Coding standard violations (if obvious)
          * Overly complex functions (high cyclomatic complexity)
          * Magic numbers/strings that should be constants
          * Dead code or unreachable code
          * Missing or incorrect error messages
        - Avoid duplicates: skip if similar feedback already exists on or near the same lines.

        Commenting rules:
        - Max 10 inline comments total; prioritize the most critical issues
        - One issue per comment; place on the exact changed line
        - All issue comments MUST be inline (anchored to a file and line/position in the PR diff)
        - Natural tone, specific and actionable; do not mention automated or high-confidence
        - Use emojis: 🚨 Critical 🔒 Security ⚡ Performance ⚠️ Logic ✅ Resolved ✨ Improvement 📋 Requirements 🏗️ Architecture 🔍 Code Quality

        Submission:
        - If there are NO issues to report and an existing top-level comment indicating "no issues" already exists (e.g., "✅ no issues", "No issues found", "LGTM"), do NOT submit another comment. Skip submission to avoid redundancy.
        - If there are NO issues to report and NO prior "no issues" comment exists, submit one brief summary comment noting no issues.
        - If there ARE issues to report and a prior "no issues" comment exists, ensure that prior comment is deleted/minimized/marked as superseded before submitting the new review.
        - If there ARE issues to report, submit ONE review containing ONLY inline comments plus an optional concise summary body. Use the GitHub Reviews API to ensure comments are inline:
        - Build a JSON array of comments like: [{ "path": "<file>", "position": <diff_position>, "body": "..." }]
        - Submit via: gh api repos/${GITHUB_REPOSITORY}/pulls/${GITHUB_PR_NUMBER}/reviews -f event=COMMENT -f body="\$SUMMARY" -f comments='[\$COMMENTS_JSON]'
        - Do NOT use: gh pr review --approve or --request-changes

        Blocking behavior:
        - If BLOCKING_REVIEW is true and any 🚨 or 🔒 issues were posted: echo "CRITICAL_ISSUES_FOUND=true" >> \$GITHUB_ENV
        - Otherwise: echo "CRITICAL_ISSUES_FOUND=false" >> \$GITHUB_ENV
        - Always set CRITICAL_ISSUES_FOUND at the end
        PROMPT
        fi

    - name: Check blocking review results
      if: ${{ inputs.blocking_review == 'true' }}
      shell: bash
      run: |
        echo "Checking for critical issues..."
        echo "CRITICAL_ISSUES_FOUND: ${CRITICAL_ISSUES_FOUND:-unset}"

        if [ "${CRITICAL_ISSUES_FOUND:-false}" = "true" ]; then
          echo "❌ Critical issues found and blocking review is enabled. Failing the workflow."
          exit 1
        else
          echo "✅ No blocking issues found."
        fi

