name: 'Cursor Code Review'
description: 'Automated code review using Cursor Agent'
inputs:
  cursor_api_key:
    description: 'Cursor API key'
    required: true
  model:
    description: 'Model to use for review'
    required: false
    default: 'auto'
  blocking_review:
    description: 'Enable blocking review (fail workflow on critical issues 🚨 or 🔒). If true, workflow will fail if critical issues are found.'
    required: false
    default: 'false'
  gh_token:
    description: 'GitHub/Gitea token for PR comments'
    required: true
  custom_prompt:
    description: 'Custom prompt to override default code review instructions. If provided, this will be used instead of the default prompt.'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Install Cursor CLI
      shell: bash
      run: |
        chmod +x "$GITHUB_ACTION_PATH/setup.sh"
        "$GITHUB_ACTION_PATH/setup.sh"

    - name: Verify Cursor CLI installation
      shell: bash
      run: |
        chmod +x "$GITHUB_ACTION_PATH/verify.sh"
        "$GITHUB_ACTION_PATH/verify.sh"

    - name: Configure git identity
      shell: bash
      run: |
        chmod +x "$GITHUB_ACTION_PATH/git-config.sh"
        "$GITHUB_ACTION_PATH/git-config.sh"

    - name: Perform automated code review
      shell: bash
      env:
        CURSOR_API_KEY: ${{ inputs.cursor_api_key }}
        MODEL: ${{ inputs.model }}
        GH_TOKEN: ${{ inputs.gh_token }}
        BLOCKING_REVIEW: ${{ inputs.blocking_review }}
        CUSTOM_PROMPT: ${{ inputs.custom_prompt }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
        GITHUB_PR_BASE_SHA: ${{ github.event.pull_request.base.sha }}
        GITHUB_SERVER_URL: ${{ github.server_url }}
      run: |
        chmod +x "$GITHUB_ACTION_PATH/run-review.sh"
        "$GITHUB_ACTION_PATH/run-review.sh"

    - name: Check blocking review results
      if: ${{ inputs.blocking_review == 'true' }}
      shell: bash
      run: |
        chmod +x "$GITHUB_ACTION_PATH/check-results.sh"
        "$GITHUB_ACTION_PATH/check-results.sh"

